sudo: required
services:
  - docker
before_install:
  - docker build -t abdulbasitnawab/docker-react-test2 -f Dockerfile.dev .
script:
  - docker run -e CI=true abdulbasitnawab/docker-react-test2 npm run test
deploy:
  provider: elasticbeanstalk
  region:  "us-east-2"
  app: "docker-react-test2"
  env: "Dockerreacttest2-env"
  bucket_name: "elasticbeanstalk-us-east-2-204520103409"
  bucket_path: "docker-react-test2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
