sudo: required
services:
  - docker
before_install:
  - docker build -t abdulbasitnawab/docker-react-test2 -f Dockerfile.dev .
script:
  - docker run -e CI=true abdulbasitnawab/docker-react-test2 npm run test 