sudo: required
services:
  - docker
before_install:
  - docker build -t abdulbasitnawab/docker-react-test2 -f Dovkerfile.dev .
script:
  - docker run abdulbasitnawab/docker-react-test2 npm run test -- --coverage